//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PredDiplom.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Группа
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Группа()
        {
            this.Студент = new HashSet<Студент>();
        }
    
        public int ИД_Группа { get; set; }
        public int ИД_Специальность { get; set; }
        public int Количество_студентов { get; set; }
        public Nullable<int> Количество_свободных_мест { get; set; }
        public string Префикс_группы { get; set; }
        public string Курс { get; set; }
        public Nullable<System.DateTime> Дата_формирования { get; set; }
        public Nullable<System.DateTime> Дата_окончания { get; set; }
        public string Классный_руководитель { get; set; }
    
        public virtual ИД_Специальность ИД_Специальность1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Студент> Студент { get; set; }
    }
}
