//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PredDiplom.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявки
    {
        public int ИД_Заявка { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public string Место_обучения { get; set; }
        public string Аттестат { get; set; }
        public string Номер_телефона { get; set; }
        public string Электронная_почта { get; set; }
        public int ИД_Статус_заявления { get; set; }
    
        public virtual ИД_Статус_заявления ИД_Статус_заявления1 { get; set; }
    }
}
