//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PredDiplom.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        public int ИД_Сотрудники { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public int ИД_Тип_сотрудника { get; set; }
        public string Почта { get; set; }
    
        public virtual Тип_сотрудники Тип_сотрудники { get; set; }
    }
}
