//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PredDiplom.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Студент
    {
        public int ИД_Студент { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public int ИД_Группа { get; set; }
        public int ИД_Статус_студента { get; set; }
        public int ИД_Форма_обучения { get; set; }
        public Nullable<System.DateTime> Дата_зачисления { get; set; }
        public Nullable<System.DateTime> Дата_выбытия { get; set; }
        public string Номер_телефона { get; set; }
        public string Изображение { get; set; }
        public int ИД_Специальность { get; set; }
        public int ИД_Преподаватель { get; set; }
    
        public virtual Группа Группа { get; set; }
        public virtual ИД_Специальность ИД_Специальность1 { get; set; }
        public virtual Преподаватель Преподаватель { get; set; }
        public virtual Статус_студента Статус_студента { get; set; }
        public virtual Форма_обучения Форма_обучения { get; set; }
    }
}
